package net.thunderbird.mail.testserver.fixture

import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * Builds one message. Address functions and [flags]/[keywords]/[header] append; the other setters replace.
 *
 * Headers are written in a fixed order: Date, From, To, Cc, Bcc, Reply-To, Subject, Message-ID, custom headers,
 * MIME-Version, then the body's Content-* headers. Exactly one body may be declared; without one the message gets an
 * empty `text/plain` body. Without a From the message is from [FixtureDefaults.SENDER]; use `raw()` for a message
 * that has none.
 */
@OptIn(ExperimentalTime::class)
@Suppress("TooManyFunctions") // DSL surface: one function per header or attribute
@FixtureDsl
class MessageBuilder internal constructor(private val messageNumber: Int) : BodyBuilder() {
    private val from = mutableListOf<String>()
    private val to = mutableListOf<String>()
    private val cc = mutableListOf<String>()
    private val bcc = mutableListOf<String>()
    private val replyTo = mutableListOf<String>()
    private var subject: String? = null
    private var date: Instant? = null
    private var messageId: String? = null
    private var internalDate: Instant? = null
    private val headers = mutableListOf<Pair<String, String>>()
    private val flags = linkedSetOf<SystemFlag>()
    private val keywords = linkedSetOf<String>()
    private var body: MimeBody? = null

    /** Each argument is one mailbox, e.g. `"Bob <bob@example.org>"` or `"bob@example.org"`. */
    fun from(vararg addresses: String) {
        from += addresses
    }

    fun to(vararg addresses: String) {
        to += addresses
    }

    fun cc(vararg addresses: String) {
        cc += addresses
    }

    fun bcc(vararg addresses: String) {
        bcc += addresses
    }

    fun replyTo(vararg addresses: String) {
        replyTo += addresses
    }

    fun subject(value: String) {
        subject = value
    }

    /** Defaults to [FixtureDefaults.BASE_DATE] plus one minute per preceding message of the same user. */
    fun date(value: Instant) {
        date = value
    }

    /** With or without angle brackets. Defaults to `<fixture-N@testserver.invalid>`. */
    fun messageId(value: String) {
        messageId = normalizeMessageId(value, "Message-ID")
    }

    /** Server-side INTERNALDATE. Defaults to the message's Date. */
    fun internalDate(value: Instant) {
        internalDate = value
    }

    /**
     * Adds an extra header. Non-ASCII values are RFC 2047 encoded. Headers with a dedicated function (or generated
     * ones like Content-Type) can't be set this way; use [FolderBuilder.raw] for full control.
     */
    fun header(name: String, value: String) {
        HeaderFormat.validateName(name)
        require(RESERVED_HEADERS.none { it.equals(name, ignoreCase = true) }) {
            "Header $name is generated by the DSL and can't be added with header()"
        }
        HeaderFormat.validateValue(value)
        headers += name to value
    }

    fun flags(vararg flags: SystemFlag) {
        this.flags += flags
    }

    fun keywords(vararg keywords: String) {
        keywords.forEach(::validateKeyword)
        this.keywords += keywords
    }

    override fun addBody(body: MimeBody) {
        check(this.body == null) { "Message body already declared; use mixed { } etc. for multiple parts" }
        this.body = body
    }

    internal fun build(): MessageFixture {
        val date = date ?: FixtureDefaults.dateFor(messageNumber)
        val messageId = messageId ?: FixtureDefaults.messageIdFor(messageNumber)
        val subject = subject

        val headerLines = buildList {
            add(HeaderFormat.field("Date", HeaderFormat.formatDate(date)))
            addAddressHeader("From", from.ifEmpty { listOf(FixtureDefaults.SENDER) })
            addAddressHeader("To", to)
            addAddressHeader("Cc", cc)
            addAddressHeader("Bcc", bcc)
            addAddressHeader("Reply-To", replyTo)
            if (subject != null) add(HeaderFormat.unstructured("Subject", subject))
            add(HeaderFormat.field("Message-ID", messageId))
            headers.forEach { (name, value) -> add(HeaderFormat.unstructured(name, value)) }
            add(HeaderFormat.field("MIME-Version", "1.0"))
        }

        val rfc822 = MimeRenderer(messageNumber).renderMessage(headerLines, body ?: textBody("plain", ""))

        return MessageFixture(
            rfc822 = rfc822,
            subject = subject,
            messageId = messageId,
            flags = flags.toSet(),
            keywords = keywords.toSet(),
            internalDate = internalDate ?: date,
        )
    }

    private fun MutableList<String>.addAddressHeader(name: String, addresses: List<String>) {
        if (addresses.isNotEmpty()) add(HeaderFormat.addressList(name, addresses))
    }

    private companion object {
        val RESERVED_HEADERS = listOf(
            "Date",
            "From",
            "To",
            "Cc",
            "Bcc",
            "Reply-To",
            "Subject",
            "Message-ID",
            "MIME-Version",
            "Content-Type",
            "Content-Transfer-Encoding",
            "Content-Disposition",
            "Content-ID",
        )
    }
}

/**
 * Functions for declaring body parts, shared by [MessageBuilder] (exactly one body) and [MultipartBuilder] (one or
 * more parts).
 *
 * Text is encoded as UTF-8 quoted-printable, with `\n`, `\r\n` and `\r` all turned into CRLF line breaks. Binary
 * content is base64 with 76-character lines.
 */
@FixtureDsl
abstract class BodyBuilder internal constructor() {
    internal abstract fun addBody(body: MimeBody)

    fun text(content: String) {
        addBody(textBody("plain", content))
    }

    fun html(content: String) {
        addBody(textBody("html", content))
    }

    fun alternative(block: MultipartBuilder.() -> Unit) {
        multipart("alternative", block)
    }

    fun mixed(block: MultipartBuilder.() -> Unit) {
        multipart("mixed", block)
    }

    fun related(block: MultipartBuilder.() -> Unit) {
        multipart("related", block)
    }

    /** A `multipart/[subtype]` body. Needs at least one part. */
    fun multipart(subtype: String, block: MultipartBuilder.() -> Unit) {
        require(MIME_TOKEN.matches(subtype)) { "Invalid multipart subtype: $subtype" }
        val parts = MultipartBuilder().apply(block).parts
        require(parts.isNotEmpty()) { "multipart/$subtype needs at least one part" }
        addBody(MultipartBody(subtype, parts.toList()))
    }

    /** Escape hatch for a single (non-multipart) part of any type. */
    fun part(mimeType: String, block: PartBuilder.() -> Unit) {
        addBody(PartBuilder(mimeType).apply(block).build())
    }

    /**
     * An attachment. With [inline] the disposition is `inline` instead of `attachment`. [contentId] (with or without
     * angle brackets) is written as `Content-ID`, e.g. for images referenced from HTML in a [related] body.
     */
    fun attachment(
        name: String,
        content: ByteArray,
        mimeType: String = "application/octet-stream",
        inline: Boolean = false,
        contentId: String? = null,
    ) {
        validateMimeType(mimeType)
        require(!mimeType.startsWith("multipart/", ignoreCase = true)) { "Use multipart { } for $mimeType" }
        HeaderFormat.validateValue(name)
        val normalizedContentId = contentId?.let { normalizeMessageId(it, "Content-ID") }

        addBody(
            LeafBody(
                mimeType = mimeType,
                parameters = listOf("name" to name),
                content = content.copyOf(),
                encoding = TransferEncoding.BASE64,
                disposition = Disposition(if (inline) "inline" else "attachment", name),
                contentId = normalizedContentId,
                extraHeaders = emptyList(),
            ),
        )
    }
}

@FixtureDsl
class MultipartBuilder internal constructor() : BodyBuilder() {
    internal val parts = mutableListOf<MimeBody>()

    override fun addBody(body: MimeBody) {
        parts += body
    }
}

/**
 * Content-Transfer-Encoding for [PartBuilder]. [SEVEN_BIT] and [EIGHT_BIT] write the content unchanged.
 */
enum class TransferEncoding(internal val headerValue: String) {
    SEVEN_BIT("7bit"),
    EIGHT_BIT("8bit"),
    QUOTED_PRINTABLE("quoted-printable"),
    BASE64("base64"),
}

/**
 * Builds a single part of any non-multipart type.
 *
 * The default encoding is [TransferEncoding.QUOTED_PRINTABLE] for `text/...`, [TransferEncoding.SEVEN_BIT] or
 * [TransferEncoding.EIGHT_BIT] (depending on the content) for `message/...`, and [TransferEncoding.BASE64] otherwise.
 * Quoted-printable treats LF and CRLF in the content as line breaks.
 */
@FixtureDsl
class PartBuilder internal constructor(private val mimeType: String) {
    private var content = ByteArray(0)
    private var isText = false
    private var encoding: TransferEncoding? = null
    private val parameters = mutableListOf<Pair<String, String>>()
    private var disposition: Disposition? = null
    private val headers = mutableListOf<Pair<String, String>>()

    init {
        validateMimeType(mimeType)
        require(!mimeType.startsWith("multipart/", ignoreCase = true)) { "Use multipart { } for $mimeType" }
    }

    fun content(bytes: ByteArray) {
        content = bytes.copyOf()
        isText = false
    }

    /** UTF-8 content. For `text/...` types a `charset=UTF-8` parameter is added unless one is set explicitly. */
    fun content(text: String) {
        content = text.toByteArray(Charsets.UTF_8)
        isText = true
    }

    /** A Content-Type parameter. */
    fun parameter(name: String, value: String) {
        require(MIME_TOKEN.matches(name)) { "Invalid parameter name: $name" }
        HeaderFormat.validateValue(value)
        parameters += name to value
    }

    fun encoding(encoding: TransferEncoding) {
        this.encoding = encoding
    }

    fun disposition(type: String, fileName: String? = null) {
        require(MIME_TOKEN.matches(type)) { "Invalid disposition type: $type" }
        fileName?.let(HeaderFormat::validateValue)
        disposition = Disposition(type, fileName)
    }

    /** An extra part header, e.g. Content-Description. Non-ASCII values are RFC 2047 encoded. */
    fun header(name: String, value: String) {
        HeaderFormat.validateName(name)
        require(RESERVED_PART_HEADERS.none { it.equals(name, ignoreCase = true) }) {
            "Header $name is generated by the DSL; use the dedicated function"
        }
        HeaderFormat.validateValue(value)
        headers += name to value
    }

    internal fun build(): LeafBody {
        val isTextType = mimeType.startsWith("text/", ignoreCase = true)
        val needsCharset = isText && isTextType && parameters.none { it.first.equals("charset", ignoreCase = true) }
        val finalParameters = if (needsCharset) listOf("charset" to "UTF-8") + parameters else parameters.toList()

        return LeafBody(
            mimeType = mimeType,
            parameters = finalParameters,
            content = content,
            encoding = encoding ?: defaultEncoding(isTextType),
            disposition = disposition,
            contentId = null,
            extraHeaders = headers.toList(),
        )
    }

    private fun defaultEncoding(isTextType: Boolean): TransferEncoding = when {
        isTextType -> TransferEncoding.QUOTED_PRINTABLE

        mimeType.startsWith("message/", ignoreCase = true) -> {
            if (content.all { it >= 0 }) TransferEncoding.SEVEN_BIT else TransferEncoding.EIGHT_BIT
        }

        else -> TransferEncoding.BASE64
    }

    private companion object {
        val RESERVED_PART_HEADERS = listOf("Content-Type", "Content-Transfer-Encoding", "Content-Disposition")
    }
}

internal sealed interface MimeBody

internal class LeafBody(
    val mimeType: String,
    val parameters: List<Pair<String, String>>,
    val content: ByteArray,
    val encoding: TransferEncoding,
    val disposition: Disposition?,
    val contentId: String?,
    val extraHeaders: List<Pair<String, String>>,
) : MimeBody

internal class Disposition(val type: String, val fileName: String?)

internal class MultipartBody(val subtype: String, val parts: List<MimeBody>) : MimeBody

internal fun textBody(subtype: String, content: String): LeafBody {
    val normalized = content.replace("\r\n", "\n").replace('\r', '\n')
    return LeafBody(
        mimeType = "text/$subtype",
        parameters = listOf("charset" to "UTF-8"),
        content = normalized.toByteArray(Charsets.UTF_8),
        encoding = TransferEncoding.QUOTED_PRINTABLE,
        disposition = null,
        contentId = null,
        extraHeaders = emptyList(),
    )
}

private val MIME_TOKEN = Regex("""[A-Za-z0-9!#$&^_.+\-]+""")

/** Adds angle brackets if missing and rejects values that aren't a single msg-id. */
private fun normalizeMessageId(value: String, headerName: String): String {
    val id = value.trim().removeSurrounding("<", ">")
    require(id.isNotEmpty() && id.all { it.isVisibleAscii() && it !in "<>" }) { "Invalid $headerName: $value" }
    return "<$id>"
}

private fun validateMimeType(mimeType: String) {
    val parts = mimeType.split('/')
    require(parts.size == 2 && parts.all { MIME_TOKEN.matches(it) }) { "Invalid MIME type: $mimeType" }
}
